const API_URL = {
  login: '/login',
  logout: '/members/logout',
  members: '/members',
  cart: '/carts',
  order: '/orders',
  nonmember: '/non-members',
  search: '/search',
  products: '/products',
  recommend: '/recommends',
  review: '/reviews',
  qna: '/qna',
  survey: '/survey',
  category: '/search/category',
  relation: '/products/relation',
  admin_products: '/admins/products',
  admin_categories: '/admins/categories',
  admin_transactions: '/admins/orders',
  curation: '/curation',
  curation_companion: '/curation/detail/companion',
  curation_gender: '/curation/detail/gender',
  curation_age: '/curation/detail/age-group',
  curation_hobby: '/curation/detail/hobby',
  curation_religion: '/curation/detail/religion',
  curation_season: '/curation/detail/season',
  wishlist: '/wishlist',
}

export default API_URL
