const PATH = {
  HOME: '/',
  CONTACT: '/contact',
  PRODUCT: '/product',
  REVIEW: '/review',
  SEARCH: '/search',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SURVEY: '/survey',
  SURVEY_RESULT: '/result',
  USER: '/user',
  PRODUCT_DETAIL: '/product/:productId',
  MYPAGE: '/mypage',
  CART: '/mypage/cart',
  ORDER_LIST: 'orderlist',
  WISHLIST: '/mypage/wishlist',
  MY_REVIEW: 'myreview',
  ONE_ON_ONE: 'oneonone',
  INFO_EDIT: 'infoedit',
  ADMIN: '/admin',
  PRODUCTS_LIST: '/admin/productsList',
  TRANSACTION_LIST: '/admin/TransactionList',
  USER_LIST: '/admin/userList',
  POST_LIST: '/admin/postList',
  PRODUCT_GROUP: '/product/group',
  PRODUCT_THEME: '/product/theme',
  PRODUCT_RECOMMEND: '/product/recommend',
  ADD_PRODUCT: '/admin/addproduct',
}

export default PATH
