const PATH = {
  HOME: '/',
  CONTACT: '/contact',
  PRODUCT: '/product',
  REVIEW: '/review',
  SEARCH: '/search',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SURVEY: '/survey',
  SURVEY_RESULT: '/result',
  PRODUCT_DETAIL: '/product/:productId',
  MYPAGE: '/mypage',
  CART: '/mypage/cart',
  BUY: '/buy',
  CONSULT: '/consult',
  ORDER_LIST: 'orderlist',
  WISHLIST: '/mypage/wishlist',
  CHECKPASSWORD: '/mypage/checkpassword',
  MY_REVIEW: 'myreview',
  ONE_ON_ONE: 'oneonone',
  INFO_EDIT: 'infoedit',
  ADMIN: '/admin',
  PRODUCTS_LIST: 'productsList',
  TRANSACTION_LIST: '/admin/transactionList',
  USER_LIST: '/admin/userlist',
  POST_LIST: '/admin/postlist',
  PRODUCT_GROUP: '/product/group',
  PRODUCT_DISTRICT: '/product/district',
  PRODUCT_THEME: '/product/theme',
  PRODUCT_RECOMMEND: '/product/recommend',
  ADD_PRODUCT: '/admin/addproduct',
  EDIT_PRODUCT: '/admin/editproduct/:productId',
}

export default PATH
